server:
  port: 7777

spring:
  application:
    name: openfeign-server
  zipkin:
    base-url: http://192.168.10.55:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
#      percentage: 1.0
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:7000/eureka,http://eureka01:7001/eureka,http://eureka02:7002/eureka

