server:
  port: 10086

spring:
  application:
    name: user-service-zuul
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1


eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:7000/eureka,http://eureka01:7001/eureka,http://eureka02:7002/eureka

zuul:
  routes:
    zuul-path:
      path: /zuul-path/**
      serviceId: USER-SERVICE-PROVIDE
    zuul-ribbon-path:
      path: /zuul-ribbon-path/**
      serviceId: USER-SERVICE-CONSUME
    zuul-consume-path:
      path: /zuul-consume-path/**
      serviceId: USER-SERVICE-CONSUME
    zuul-openfeign-path:
      path: /zuul-openfeign-path/**
      serviceId: OPENFEIGN-SERVER