server:
  port: 80

spring:
  application:
    name: user-service-consume
  zipkin:
    base-url: http://192.168.231.128:9411
    enabled: true
    discovery-client-enabled: true
  sleuth:
    sampler:
      probability: 1


eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:7000/eureka,http://eureka01:7001/eureka,http://eureka02:7002/eureka