server:
  port: 8087

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hacker
    password: Rqh17879303721
    url: jdbc:mysql://raoqinhao.mysql.rds.aliyuncs.com:3306/user?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true

mybatis-plus:
  global-config:
    id-type: 1
    db-column-underline: true
    db-type: MYSQL
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
  type-aliases-package: com.hh.userservice.pojo
  mapper-locations: classpath:mappers/*.xml
