server:
  port: 9002

spring:
  application:
    name: user-service-provide
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hacker
    password: Rqh17879303721
    url: jdbc:mysql://raoqinhao.mysql.rds.aliyuncs.com:3306/user?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true

mybatis:
  typeAliasesPackage: com.hh.userserviceprovide02.pojo
  mapper-locations: mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:7000/eureka,http://eureka01:7001/eureka,http://eureka02:7002/eureka

