server:
  port: 8848

spring:
  data:
    mongodb:
      username: admin
      authentication-database: admin
      database: user
      password: '123456'
      host: 192.168.10.55
      port: 27017
#      uri: mongodb://admin:123456:27017/?authSource=admin

