server:
  port: 8086
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hacker
    password: Rqh17879303721
    url: jdbc:mysql://raoqinhao.mysql.rds.aliyuncs.com:3306/user
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  redis:
    host: 192.168.10.55
    port: 6379
    database: 0
mybatis:
  mapper-locations: mappers/*.xml

jasypt:
  encryptor:
    #这里可以理解成是加解密的时候使用的密钥
    password: lqld
