server:
  port: 8086
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: mysql:jdbc://103.75.2.32:3306/
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    #热部署文件，页面不产生缓存，及时更新
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**