server:
  port: 8086
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: qwer
    url: jdbc:mysql://101.200.204.106:3306/demo
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
mybatis:
  mapper-locations: mappers/*.xml