server:
  port: 7777

spring:
  application:
    name: user-service-activiti
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hacker
    password: Rqh17879303721
    url: jdbc:mysql://raoqinhao.mysql.rds.aliyuncs.com:3306/activiti?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
  activiti:
    database-schema-update: true
    history-level: full
    db-history-used: true

mybatis:
  mapper-locations: mappers/*.xml

logging:
  level:
    com.ascendant: debug